#====== Window Info =====
WIDTH = 1500
HEIGHT = 800

#====== Border Info =====
BORDER_RADIUS = HEIGHT * 0.65
OUTER_BORDER_RADIUS = BORDER_RADIUS * 9
BORDER_COLOR = (200,250,250)

BORDER_THICKNESS = 20
OUTER_BORDER_THICKNESS = 4160

# ===== PARTICLE COUNTS =====
NUM_QUARKS = 20

# ===== MERGE MECHANICS =====
MERGE_DISTANCE = 15
MERGE_SPEED_THRESHOLD = 12

# ===== PHYSICS MULTIPLIERS =====
GRAVITY_RANGE = 20
GRAVITY_STRENGTH = 120
optimal_speed_quarks = 2

# ===== Camera =====
DEFAULT_ZOOM = 1.2
ZOOM_MIN = 0.3
ZOOM_MAX = 5.0
ZOOM_STEP = 1.03

DISTANCE_MULTIPLIER = 0.6
MAX_OFFSET = 1200
RESPONSIVENESS = 0.05